// The glossary: every idea the campaign teaches, in plain language. Hints, the post-run explanation
// and the in-game glossary all point at these entries by id.
export interface Concept { id: string; term: string; short: string; why: string }

export const CONCEPTS: Concept[] = [
  { id: "capacity", term: "Capacity", short: "How many requests per second one machine can handle.",
    why: "Past its capacity a server cannot go faster. Extra requests wait in line, and the line has a limit." },
  { id: "overload", term: "Overload", short: "More requests arrive than a machine can serve.",
    why: "Waiting time grows, then requests are dropped. Red, pulsing nodes in the game are overloaded." },
  { id: "load-balancer", term: "Load balancer", short: "Spreads incoming requests across several servers.",
    why: "It turns many small servers into one big one, and skips servers that have died." },
  { id: "horizontal-scaling", term: "Horizontal scaling", short: "Add more machines instead of buying a bigger one.",
    why: "It has no ceiling from a single box, and it survives one machine failing. It costs money per box." },
  { id: "spof", term: "Single point of failure", short: "One part that, if it breaks, takes the whole system down.",
    why: "One API server, one database, one anything. Redundancy removes it." },
  { id: "cache", term: "Cache", short: "Fast memory that remembers recent answers.",
    why: "Popular requests are answered from memory, so the database only sees the misses. A cache is small, so it must decide what to forget." },
  { id: "hit-rate", term: "Hit rate", short: "The share of reads a cache answers itself.",
    why: "At 80% hit rate the database sees one fifth of the reads. Small changes near 100% matter a lot." },
  { id: "eviction", term: "Eviction", short: "How a full cache chooses what to throw away.",
    why: "LRU drops the entry unused for longest, LFU the least often used, FIFO the oldest. Popular-key traffic favours LFU." },
  { id: "p50", term: "p50 (median)", short: "Half of requests are faster than this.",
    why: "It describes the typical request, and hides the unlucky ones." },
  { id: "p99", term: "p99", short: "99 out of 100 requests are faster than this. The slowest 1% are slower.",
    why: "Users hit the slow tail often: a page makes many requests. Queues build in the tail first, so p99 warns you before averages do." },
  { id: "latency", term: "Latency", short: "How long a request takes, start to finish.",
    why: "Each hop adds time. Distance adds time too, which is why content is served from nearby." },
  { id: "queue", term: "Queue", short: "A waiting line that holds work until something can do it.",
    why: "It absorbs a burst of writes so the database can catch up at its own speed. Trade-off: the write is stored a moment later." },
  { id: "async", term: "Asynchronous work", short: "Say yes now, do the work later.",
    why: "The user gets an instant answer; the slow part happens in the background." },
  { id: "backpressure", term: "Backpressure", short: "A full downstream part slows or stops the sender.",
    why: "A queue only helps if its consumers eventually keep up. A full buffer starts rejecting work." },
  { id: "headroom", term: "Headroom", short: "Spare capacity above normal load.",
    why: "A machine at 95% has nowhere to go when traffic bumps. Aim for 60 to 70% at peak." },
  { id: "hot-key", term: "Hot key", short: "One item that gets a huge share of the traffic.",
    why: "It overloads whatever stores it. Adding shards cannot split one key, but a tiny cache absorbs it." },
  { id: "sharding", term: "Sharding", short: "Split data across databases by key.",
    why: "Each database handles a slice of the writes, so total write capacity multiplies. Uneven keys make uneven shards." },
  { id: "thundering-herd", term: "Thundering herd", short: "Many requests miss at once and all hit the database together.",
    why: "It happens when a cache empties or a hot entry expires. The database sees a stampede it was never sized for." },
  { id: "coalescing", term: "Request coalescing", short: "Concurrent misses for one key share a single database read.",
    why: "One request fetches, the rest wait for its answer. The database sees one read instead of thousands." },
  { id: "replica", term: "Read replica", short: "A live copy of the database that serves reads.",
    why: "Reads spread across copies, so read capacity multiplies. Writes still go to the primary." },
  { id: "replication-lag", term: "Replication lag", short: "A replica is slightly behind the primary.",
    why: "A read right after a write may return the old value. That is the price of scaling reads." },
  { id: "failover", term: "Failover", short: "Promote a standby to take over when the primary dies.",
    why: "It is not instant: the system must notice the failure, then promote. During that gap writes fail unless something holds them." },
  { id: "health-check", term: "Health check", short: "A regular ping that finds dead machines.",
    why: "Until the next check, a balancer still sends traffic to a machine that is already down." },
  { id: "cdn", term: "CDN", short: "Servers near users that cache static files.",
    why: "Images and scripts are served from the edge, close to the user, and your own servers never see those requests." },
  { id: "static-assets", term: "Static assets", short: "Files that are the same for everyone: images, scripts, styles.",
    why: "They are perfect to cache, since nothing about them is personal." },
  { id: "rate-limiter", term: "Rate limiter", short: "Caps how many requests each client may send.",
    why: "It protects the servers from a few abusive clients so everyone else still gets through." },
  { id: "token-bucket", term: "Token bucket", short: "Each client has a bucket that refills steadily; each request spends a token.",
    why: "Bursts are allowed up to the bucket size, but sustained flooding runs dry." },
  { id: "fairness", term: "Fairness", short: "Every client gets a similar share.",
    why: "Per-client limits punish only the heavy senders. A global limit would punish everybody." },
  { id: "message-broker", term: "Message broker", short: "A durable inbox that holds jobs until workers take them.",
    why: "It decouples accepting work from doing it, so a burst does not overwhelm the workers." },
  { id: "worker-pool", term: "Worker pool", short: "Several machines that pull jobs from a queue.",
    why: "Add workers to drain a backlog faster. Too many can overwhelm the database behind them." },
  { id: "chaos", term: "Failure injection", short: "Breaking things on purpose to see what happens.",
    why: "Real systems fail. Testing failure early shows which designs recover and which do not." },
];

export const CONCEPT_MAP = new Map(CONCEPTS.map((c) => [c.id, c]));
export function concept(id: string): Concept | undefined { return CONCEPT_MAP.get(id); }

/** One-line explanation of each part, shown when you tap it on the shelf or the board. */
export const KIND_INFO: Record<string, string> = {
  client: "Users: the source of all traffic. Everything flows from here.",
  lb: "Load balancer: spreads requests across servers and skips dead ones.",
  api: "API server: runs your code. Handles about 400 requests a second.",
  cache: "Cache: memory that answers popular reads. Tap it to change size and eviction.",
  db: "Database: the source of truth. Slow, and limited to about 300 requests a second.",
  queue: "Queue: holds bursts of writes and hands them to the database at its pace.",
  replica: "Read replica: a copy of the database that serves reads. Can lag slightly.",
  cdn: "CDN: caches static files near users so your servers never see them.",
  limiter: "Rate limiter: gives each client an allowance and rejects the excess.",
  shard: "Shard router: sends each key to one of several databases.",
  broker: "Message broker: a durable inbox. Acknowledges jobs instantly, workers take them later.",
  worker: "Worker pool: pulls jobs from the broker and does the slow work.",
};
